version: '3.1'

services:
  db:
    container_name: posgresql
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: request_counter_service_db
    ports:
      - "5432:5432"
